### ISSUE TITLE
Extensions in extension manager cannot be installed

### ISSUE THREAD

**Issue by RafaelPalomar** [RafaelPalomar/org.slicer.Slicer-flatpak-repository#2]
![screenshot](https://github.com/RafaelPalomar/org.slicer.Slicer-flatpak-repository/assets/1978682/5aa520ad-f039-46cb-8ae3-acc41a5d51b3)

It seems that Slicer is trying to create directories on the application space, possibly without permissions. Need to check whether we can point Slicer to create directories somewhere else.

Update 1: https://discourse.slicer.org/t/unable-to-install-extensions-when-slicer-is-installed-in-system-location/16588/2?u=rafaelpalomar

Update 2: I suppose the path is computed in compile time (build environment), which leads to a non-usable directory in runtime

**Comment by umgpy** [comment]
I am able to see the extension page now and install the extensions, however the some of installed extensions do not get loaded m (Monai Label and SlicerRT). SlicerIGT is loading properly, I believe this could be possibly due to issues with SimpleITK amongst others.

I have attached the error log here.
 
[flatpak_extention_error.log](https://github.com/RafaelPalomar/org.slicer.Slicer-flatpak-repository/files/11871479/flatpak_extention_error.log)
